
# Create the network so that our containers can talk to eachother
networks:
    bootcamp:
      name: bootcamp_net
      driver: bridge

# Create the storage volume for our cache
volumes:
    cache_data:
        name: cache_data

# Define our containers
services:

    # Define cache properties
    cache:
        image: 'valkey/valkey:8-alpine'
        volumes:
            - cache_data:/data
        networks:
            - bootcamp

    # Define python app properties, have it build our image
    app:
        build:
            context: .
        networks:
            - bootcamp
        environment:
            CACHE_HOST: ${CACHE_HOST:-cache}
        entrypoint: "/bin/sh"
        tty: true
        develop:
            watch:
                - action: sync
                  path: .
                  target: /app
                - action: rebuild
                  path: requirements.txt
        healthcheck:
            test: ["CMD", "python", "cache_client.py", "check_cache"]
            interval: 3s
